### ISSUE TITLE
Error Log on 1.0.3 Install. 

### ISSUE THREAD

**Issue by cloudzombie** [psychobunny/nodebb-plugin-paypal-subscriptions#6]
```
13/5 16:44 [13840] - [31merror[39m: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-paypal-subscriptions'
13/5 16:44 [13840] - [31merror[39m:  ReferenceError: controllers is not defined
    at Object.module.init [as method] (/home/cloud/NodeBB/node_modules/nodebb-plugin-paypal-subscriptions/library.js:58:75)
    at /home/cloud/NodeBB/src/plugins/hooks.js:147:14
    at /home/cloud/NodeBB/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/cloud/NodeBB/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/cloud/NodeBB/node_modules/async/lib/async.js:209:22)
    at fireStaticHook (/home/cloud/NodeBB/src/plugins/hooks.js:136:9)
    at Object.Plugins.fireHook (/home/cloud/NodeBB/src/plugins/hooks.js:82:5)
    at Plugins.reloadRoutes (/home/cloud/NodeBB/src/plugins.js:143:11)
    at /home/cloud/NodeBB/node_modules/async/lib/async.js:760:23
    at /home/cloud/NodeBB/node_modules/async/lib/async.js:166:37

```

**Comment by theunknownartisthour** [comment]
The plugin isn't functional yet\* but see if the error is solved with:
https://github.com/theunknownartisthour/nodebb-plugin-paypal-subscriptions.git

This is the repo I'm working from.
